// Generated by CoffeeScript 1.4.0
(function() {
  var main, writeMain, writeTitle;

  $(window).ready(function() {
    return main();
  });

  main = function() {
    window.container = $('.container');
    return writeTitle();
  };

  writeTitle = function() {
    var gravatar, header_container, title, title_container;
    header_container = $('.header-container');
    title_container = $('<div class="centered title-container"></div>').appendTo(header_container);
    gravatar = new window.Gravatar("img/da-gravatar.jpg");
    title_container.append(gravatar.el);
    title = $('<h1 id="my-name" class="animated fadeInDown">David Adler</h1>');
    title.on('click', function(event) {
      event.preventDefault();
      return location.reload();
    });
    title.hover(function(e) {
      return $('#gravatar');
    });
    title_container.append(title);
    return header_container.delay(1000).animate({
      height: '10em'
    }, {
      duration: 700,
      complete: function() {
        return gravatar.show(writeMain);
      }
    });
  };

  writeMain = function() {
    var cv_sections, data, main_container, sect, _i, _len, _ref;
    main_container = "<div class=\"animated fadeInUpBig main-container\">\n    <div class=\"main wrapper clearfix \">\n    </div>\n</div>";
    window.converter = new Markdown.Converter();
    window.converter.hooks.chain("preConversion", function(text) {
      return text.replace(/(\w*)-(\w*)\[(.*)]/gi, "<$1 class='$2'>$3</$1>");
    });
    window.converter.hooks.chain("preConversion", function(text) {
      return text.replace(/graph-(\d\d\d?)%/gi, '<div style="width:30em"><div class="animated graph" style="width: $1%;"></div></div>');
    });
    window.container.append(main_container);
    cv_sections = [];
    _ref = window.cv_sections;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      data = _ref[_i];
      sect = new window.Section(data.icon, data.title, data.description, data.content);
      cv_sections.push(sect.render());
    }
    $('.main').append(cv_sections);
    return $('span.fill').hover(function(e) {
      return $(e.target).parent().parent().parent().css({
        backgroundColor: 'rgba(128, 128, 128, 0.1)',
        opacity: 0.8
      });
    }, function(e) {
      return $(e.target).parent().parent().parent().css({
        backgroundColor: 'transparent',
        opacity: 1
      });
    });
  };

}).call(this);
